# SPDX-FileCopyrightText: 2023 SAP SE
#
# SPDX-License-Identifier: Apache-2.0
#
# This file is part of FEDEM - https://openfedem.org

name: Unit testing

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and execute unit tests

    runs-on: ubuntu-latest

    steps:
      - name: Install googletest
        uses: Bacondish2023/setup-googletest@v1

      - name: Silence some advice and hint and set environment variables
        run: |
          git config --global advice.detachedHead false
          git config --global init.defaultBranch main
          echo "LD_LIBRARY_PATH=${{ github.workspace }}/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "FEDEM_REDUCER=${{ github.workspace }}/bin/libfedem_reducer_core.so" >> $GITHUB_ENV
          echo "FEDEM_SOLVER=${{ github.workspace }}/bin/libfedem_solver_core.so" >> $GITHUB_ENV
          echo "TEST_DIR=${{ github.workspace }}/fedem-solver-tests/TimeDomain" >> $GITHUB_ENV

      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check out the solver tests
        uses: actions/checkout@v4
        with:
          repository: openfedem/fedem-solver-tests
          sparse-checkout: TimeDomain

      - name: Download the latest FEDEM release
        uses: robinraju/release-downloader@v1
        with:
          repository: openfedem/fedem-solvers
          fileName: 'fedem-*_linux64.tar.gz'
          latest: true
          extract: true

      - name: Download the latest fedempy release
        id: fedempy
        uses: robinraju/release-downloader@v1
        with:
          repository: openfedem/fedem-solvers
          fileName: 'fedempy-*.tar.gz'
          latest: true

      - name: Configure pFUnit-3
        run: >
          PFUNIT=./pFUnit3 cmake
          -B ./pFUnit3-build -S ./fedem-foundation/pFUnit/pFUnit-3.3.3
          -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./pFUnit3

      - name: Build and install pFUnit-3
        run: cmake --build ./pFUnit3-build --target install

      - name: Install the fedempy package
        run: pip install ${{ fromJson(steps.fedempy.outputs.downloaded_files)[0] }}

      - name: Configure main build
        run: >
          GTEST_ROOT=/usr/local PFUNIT=./pFUnit3 cmake -B ./build
          -DCMAKE_BUILD_TYPE=Release -DUSE_FORTRAN=ON -DUSE_CHSHAPE=ON

      - name: Build binaries and execute tests
        run: cmake --build ./build --target check
