# SPDX-FileCopyrightText: 2023 SAP SE
#
# SPDX-License-Identifier: Apache-2.0
#
# This file is part of FEDEM - https://openfedem.org

name: Unit testing

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and execute unit tests

    runs-on: ubuntu-latest

    steps:
      - name: Install googletest
        uses: Bacondish2023/setup-googletest@v1

      - name: Check out source code repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure pFUnit-3
        run: >
          PFUNIT=./pFUnit3 cmake
          -B ./pFUnit3-build -S ./fedem-foundation/pFUnit/pFUnit-3.3.3
          -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./pFUnit3

      - name: Build and install pFUnit-3
        run: cmake --build ./pFUnit3-build --target install

      - name: Configure main build
        run: >
          GTEST_ROOT=/usr/local PFUNIT=./pFUnit3 cmake -B ./build
          -DCMAKE_BUILD_TYPE=Release -DUSE_FORTRAN=ON -DUSE_CHSHAPE=ON

      - name: Build binaries and execute tests
        run: cmake --build ./build --target check
